database_server:
  host: localhost
  port: 27017
  database_name: product
  collection_name: product
  username: root
  password: admin
external_api:
  url: https://redsky.target.com/redsky_aggregations/v1/redsky/case_study_v1
  key: 3yUxt7WltYG7MFKPp7uyELi1K40ad2ys
load_seed_data: true